# Generated by Django 5.1.15 on 2026-08-26 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='BuyZo', max_length=120)),
                ('tagline', models.CharField(default='Shop More, Save More', max_length=200)),
                ('support_email', models.EmailField(default='support@buyzo.com', max_length=254)),
                ('support_phone', models.CharField(default='+91 98765 43210', max_length=20)),
                ('currency', models.CharField(choices=[('INR', 'INR (Rupee)'), ('USD', 'USD (Dollar)'), ('EUR', 'EUR (Euro)'), ('GBP', 'GBP (Pound)')], default='INR', max_length=3)),
                ('auto_approve_orders', models.BooleanField(default=True)),
                ('auto_approve_limit', models.DecimalField(decimal_places=2, default=5000, max_digits=10)),
                ('email_low_stock_alerts', models.BooleanField(default=True)),
                ('free_delivery_threshold', models.DecimalField(decimal_places=2, default=499, max_digits=10)),
                ('low_stock_threshold', models.PositiveIntegerField(default=10)),
                ('cod_enabled', models.BooleanField(default=True)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_setting_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Store Setting',
                'verbose_name_plural': 'Store Settings',
                'db_table': 'store_settings',
            },
        ),
    ]
