"""
Fashion, beauty and lifestyle catalogue data for ``seed_marketplace``.

Same tuple shape as ``_marketplace_tech``:
    (title, brand, subcategory, base_price, discount_price, image, tags, specs)
"""

# ---------------------------------------------------------------------------
# FASHION  (subcategories: Women's Wear, Men's Wear, Ethnic Wear, Accessories)
# ---------------------------------------------------------------------------
FASHION = [
    ("Women's Floral Fit & Flare Summer Dress", "Zara", "Women's Wear", 2499, 1499, "women_dress.jpg",
     "women dress floral fit flare summer", {"Fabric": "Rayon Blend", "Pattern": "Floral Print", "Sleeve": "Short Sleeve", "Care": "Machine Wash"}),
    ("Women's Solid A-Line Midi Cotton Dress", "Vero Moda", "Women's Wear", 2999, 1699, "women_dress.jpg",
     "women dress a-line midi cotton", {"Fabric": "100% Cotton", "Length": "Midi", "Neck": "Round Neck", "Care": "Machine Wash"}),
    ("Women's Ribbed Bodycon Knit Dress", "H&M", "Women's Wear", 2199, 1099, "women_dress.jpg",
     "women dress bodycon ribbed knit", {"Fabric": "Viscose Rib Knit", "Fit": "Bodycon", "Sleeve": "Sleeveless", "Care": "Hand Wash"}),
    ("Women's Puff Sleeve Wrap Maxi Dress", "AND", "Women's Wear", 3499, 2099, "women_dress.jpg",
     "women dress wrap maxi puff sleeve", {"Fabric": "Georgette", "Length": "Maxi", "Closure": "Wrap Tie", "Care": "Dry Clean"}),
    ("Women's Oversized Cotton Crewneck Sweatshirt", "H&M", "Women's Wear", 1999, 999, "fashion_sweatshirt.jpg",
     "women sweatshirt oversized crewneck cotton", {"Fabric": "Cotton Fleece", "Fit": "Oversized", "Neck": "Crewneck", "Care": "Machine Wash"}),
    ("Women's High-Rise Skinny Fit Denim Jeans", "Levi's", "Women's Wear", 3499, 1999, "fashion_chinos.jpg",
     "women jeans denim skinny high rise", {"Fabric": "Stretch Denim", "Rise": "High Rise", "Fit": "Skinny", "Care": "Machine Wash Cold"}),
    ("Men's Oxford Cotton Casual Slim Fit Shirt", "Roadster", "Men's Wear", 1799, 899, "roadster_shirt.jpg",
     "men shirt oxford cotton casual slim", {"Fabric": "Cotton Oxford", "Fit": "Slim Fit", "Collar": "Button Down", "Care": "Machine Wash"}),
    ("Men's US Polo Assn. Solid Cotton Polo T-Shirt", "U.S. Polo Assn.", "Men's Wear", 1999, 1199, "us_polo_tshirt.jpg",
     "men polo tshirt cotton us polo", {"Fabric": "Pique Cotton", "Fit": "Regular", "Collar": "Polo", "Care": "Machine Wash"}),
    ("Men's Straight Fit Stretch Cotton Chinos", "Levi's", "Men's Wear", 2799, 1699, "fashion_chinos.jpg",
     "men chinos trousers straight cotton", {"Fabric": "Cotton Stretch Twill", "Fit": "Straight", "Closure": "Zip Fly", "Care": "Machine Wash"}),
    ("Men's Washed Denim Trucker Jacket", "Levi's", "Men's Wear", 4999, 2999, "fashion_denim_jacket.jpg",
     "men jacket denim trucker washed", {"Fabric": "100% Cotton Denim", "Fit": "Regular", "Closure": "Button Front", "Care": "Machine Wash"}),
    ("Men's Fleece Crewneck Pullover Sweatshirt", "Puma", "Men's Wear", 2499, 1299, "fashion_sweatshirt.jpg",
     "men sweatshirt fleece crewneck pullover", {"Fabric": "Cotton Poly Fleece", "Fit": "Regular", "Neck": "Crewneck", "Care": "Machine Wash"}),
    ("Men's Round Neck Half Sleeve Cotton T-Shirt Pack of 2", "Jockey", "Men's Wear", 1499, 749, "us_polo_tshirt.jpg",
     "men tshirt cotton round neck pack", {"Fabric": "Combed Cotton", "Pack": "2 Pieces", "Neck": "Round Neck", "Care": "Machine Wash"}),
    ("Men's Slim Fit Formal Cotton Trousers", "Van Heusen", "Men's Wear", 2999, 1799, "fashion_chinos.jpg",
     "men formal trousers slim cotton", {"Fabric": "Poly Viscose", "Fit": "Slim Fit", "Closure": "Hook & Zip", "Care": "Dry Clean"}),
    ("Men's Checked Flannel Casual Overshirt", "Roadster", "Men's Wear", 2199, 1099, "roadster_shirt.jpg",
     "men shirt flannel checked overshirt", {"Fabric": "Brushed Flannel", "Fit": "Relaxed", "Pattern": "Checked", "Care": "Machine Wash"}),
    ("Biba Women's Printed Anarkali Kurta with Dupatta", "Biba", "Ethnic Wear", 3299, 1799, "biba_kurta.jpg",
     "biba kurta anarkali ethnic dupatta", {"Fabric": "Rayon", "Set": "Kurta + Dupatta", "Length": "Calf Length", "Care": "Hand Wash"}),
    ("Women's Embellished Silk Blend Straight Kurti", "W for Woman", "Ethnic Wear", 2799, 1599, "fashion_silk_kurti.jpg",
     "women kurti silk embellished ethnic", {"Fabric": "Silk Blend", "Work": "Embellished Yoke", "Fit": "Straight", "Care": "Dry Clean"}),
    ("Women's Cotton Printed Palazzo Kurta Set", "Biba", "Ethnic Wear", 3999, 2299, "biba_kurta.jpg",
     "women kurta palazzo set cotton ethnic", {"Fabric": "Cotton Cambric", "Set": "Kurta + Palazzo", "Pattern": "Printed", "Care": "Machine Wash"}),
    ("Women's Banarasi Art Silk Saree with Blouse Piece", "Kalini", "Ethnic Wear", 4999, 2199, "fashion_silk_kurti.jpg",
     "women saree banarasi silk ethnic", {"Fabric": "Art Silk", "Length": "5.5m + Blouse", "Work": "Zari Woven", "Care": "Dry Clean"}),
    ("Men's Cotton Blend Straight Kurta with Churidar", "Manyavar", "Ethnic Wear", 3999, 2499, "roadster_shirt.jpg",
     "men kurta churidar ethnic cotton", {"Fabric": "Cotton Blend", "Set": "Kurta + Churidar", "Fit": "Straight", "Care": "Machine Wash"}),
    ("Women's Chikankari Embroidered Cotton Kurta", "W for Woman", "Ethnic Wear", 2499, 1399, "biba_kurta.jpg",
     "women kurta chikankari embroidered cotton", {"Fabric": "Cotton", "Work": "Chikankari Embroidery", "Sleeve": "3/4th", "Care": "Hand Wash"}),
    ("Fastrack Analog Leather Strap Men's Watch", "Fastrack", "Accessories", 2995, 1795, "noise_smartwatch.jpg",
     "fastrack watch analog leather men", {"Movement": "Quartz Analog", "Strap": "Genuine Leather", "Water Resistance": "50m", "Warranty": "1 Year"}),
    ("Titan Neo Rose Gold Women's Bracelet Watch", "Titan", "Accessories", 5495, 3795, "noise_smartwatch.jpg",
     "titan watch women rose gold bracelet", {"Movement": "Quartz Analog", "Strap": "Stainless Steel", "Dial": "Mother of Pearl", "Warranty": "2 Years"}),
    ("Ray-Ban Aviator Classic Polarised Sunglasses", "Ray-Ban", "Accessories", 9490, 7590, "noise_smartwatch.jpg",
     "rayban sunglasses aviator polarised", {"Lens": "Polarised G-15", "Frame": "Metal", "UV Protection": "100%", "Warranty": "2 Years"}),
    ("Men's Reversible Genuine Leather Formal Belt", "Hidesign", "Accessories", 2495, 1495, "lavie_handbag.jpg",
     "men belt leather reversible formal", {"Material": "Full Grain Leather", "Width": "35mm", "Buckle": "Reversible Pin", "Care": "Wipe Clean"}),
    ("Women's Woven Cotton Scarf & Stole Set", "Zara", "Accessories", 1299, 699, "fashion_silk_kurti.jpg",
     "women scarf stole cotton woven", {"Fabric": "Woven Cotton", "Size": "180 x 70cm", "Pack": "2 Pieces", "Care": "Hand Wash"}),
]

# ---------------------------------------------------------------------------
# FOOTWEAR
# ---------------------------------------------------------------------------
FOOTWEAR = [
    ("Puma Flyer Flex Men's Running Shoes", "Puma", "Sports Shoes", 4499, 2249, "puma_shoes.jpg",
     "puma shoes running men flyer flex", {"Upper": "Mesh", "Sole": "SoftFoam+", "Closure": "Lace-Up", "Warranty": "90 Days"}),
    ("Nike Revolution 7 Men's Road Running Shoes", "Nike", "Sports Shoes", 4295, 3195, "puma_shoes.jpg",
     "nike shoes running revolution men", {"Upper": "Recycled Mesh", "Sole": "Soft Foam", "Drop": "9mm", "Warranty": "90 Days"}),
    ("Adidas Duramo SL Men's Training Shoes", "Adidas", "Sports Shoes", 4999, 2999, "puma_shoes.jpg",
     "adidas shoes training duramo men", {"Upper": "Textile Mesh", "Sole": "Lightmotion EVA", "Closure": "Lace-Up", "Warranty": "90 Days"}),
    ("Asics Gel-Contend 8 Men's Cushioned Running Shoes", "Asics", "Sports Shoes", 5999, 4199, "puma_shoes.jpg",
     "asics shoes gel running cushioned", {"Upper": "Engineered Mesh", "Cushioning": "GEL Technology", "Sole": "AmpliFoam", "Warranty": "6 Months"}),
    ("Puma Softride Women's Walking Shoes", "Puma", "Sports Shoes", 4999, 2499, "puma_shoes.jpg",
     "puma shoes women walking softride", {"Upper": "Knit Mesh", "Sole": "Softride Foam", "Closure": "Lace-Up", "Warranty": "90 Days"}),
    ("Red Tape Men's Chunky Sole Streetwear Sneakers", "Red Tape", "Sneakers", 3999, 1799, "fashion_street_sneakers.jpg",
     "red tape sneakers chunky streetwear men", {"Upper": "PU Leather", "Sole": "Chunky EVA", "Closure": "Lace-Up", "Warranty": "3 Months"}),
    ("Adidas Grand Court 2.0 Classic Sneakers", "Adidas", "Sneakers", 5499, 3299, "fashion_street_sneakers.jpg",
     "adidas sneakers grand court classic", {"Upper": "Synthetic Leather", "Sole": "Rubber Cupsole", "Style": "Court Classic", "Warranty": "90 Days"}),
    ("Nike Court Vision Low Next Nature Sneakers", "Nike", "Sneakers", 5495, 3846, "fashion_street_sneakers.jpg",
     "nike sneakers court vision low", {"Upper": "Recycled Leather", "Sole": "Rubber", "Style": "Retro Basketball", "Warranty": "90 Days"}),
    ("Converse Chuck Taylor All Star Canvas High Top", "Converse", "Sneakers", 3999, 2799, "fashion_street_sneakers.jpg",
     "converse chuck taylor canvas sneakers", {"Upper": "Canvas", "Sole": "Vulcanised Rubber", "Style": "High Top", "Warranty": "3 Months"}),
    ("Campus Men's Lightweight Casual Sneakers", "Campus", "Sneakers", 2199, 1099, "fashion_street_sneakers.jpg",
     "campus sneakers casual lightweight men", {"Upper": "Mesh", "Sole": "Phylon", "Weight": "260g", "Warranty": "3 Months"}),
    ("Bata Men's Formal Leather Derby Shoes", "Bata", "Formal Shoes", 3499, 1999, "puma_shoes.jpg",
     "bata formal shoes leather derby men", {"Upper": "Genuine Leather", "Sole": "TPR", "Toe": "Round Toe", "Warranty": "6 Months"}),
    ("Hush Puppies Men's Slip-On Leather Loafers", "Hush Puppies", "Formal Shoes", 5999, 3599, "puma_shoes.jpg",
     "hush puppies loafers leather slip on", {"Upper": "Soft Leather", "Sole": "Flexible Rubber", "Closure": "Slip-On", "Warranty": "6 Months"}),
    ("Ruosh Men's Brogue Oxford Formal Shoes", "Ruosh", "Formal Shoes", 6999, 4199, "puma_shoes.jpg",
     "ruosh oxford brogue formal shoes", {"Upper": "Full Grain Leather", "Sole": "Leather Welted", "Toe": "Brogue Cap", "Warranty": "6 Months"}),
    ("Crocs Classic Clog Unisex Slip-On", "Crocs", "Casual Footwear", 3995, 2796, "puma_shoes.jpg",
     "crocs clog classic slip on unisex", {"Material": "Croslite Foam", "Fit": "Roomy", "Ventilation": "Yes", "Care": "Rinse Clean"}),
    ("Woodland Men's Leather Outdoor Sandals", "Woodland", "Casual Footwear", 2795, 1795, "puma_shoes.jpg",
     "woodland sandals leather outdoor men", {"Upper": "Nubuck Leather", "Sole": "Rubber Lug", "Closure": "Velcro", "Warranty": "3 Months"}),
    ("Bata Women's Comfort Wedge Sandals", "Bata", "Casual Footwear", 1999, 999, "puma_shoes.jpg",
     "bata sandals women wedge comfort", {"Upper": "Synthetic", "Heel": "40mm Wedge", "Sole": "Cushioned EVA", "Warranty": "3 Months"}),
    ("Puma Unisex Sliders with Softride Footbed", "Puma", "Casual Footwear", 1999, 899, "puma_shoes.jpg",
     "puma sliders flip flop unisex", {"Upper": "Synthetic Strap", "Footbed": "Softride", "Sole": "EVA", "Warranty": "90 Days"}),
    ("Sparx Men's Running Sports Shoes", "Sparx", "Sports Shoes", 1799, 899, "puma_shoes.jpg",
     "sparx shoes running sports men budget", {"Upper": "Mesh", "Sole": "EVA", "Closure": "Lace-Up", "Warranty": "3 Months"}),
    ("Skechers Go Walk Flex Women's Slip-On Shoes", "Skechers", "Casual Footwear", 6499, 4549, "puma_shoes.jpg",
     "skechers go walk slip on women", {"Upper": "Engineered Mesh", "Insole": "Air Cooled Goga Mat", "Closure": "Slip-On", "Warranty": "6 Months"}),
    ("Reebok Men's Court Advance Tennis Shoes", "Reebok", "Sports Shoes", 4599, 2299, "puma_shoes.jpg",
     "reebok shoes tennis court advance", {"Upper": "Synthetic Leather", "Sole": "Non-Marking Rubber", "Closure": "Lace-Up", "Warranty": "90 Days"}),
    ("Metro Women's Embellished Ethnic Juttis", "Metro", "Casual Footwear", 2490, 1490, "puma_shoes.jpg",
     "metro juttis ethnic embellished women", {"Upper": "Embroidered Fabric", "Sole": "TPR", "Closure": "Slip-On", "Care": "Wipe Clean"}),
    ("Nike Air Max SC Men's Lifestyle Sneakers", "Nike", "Sneakers", 7495, 5246, "fashion_street_sneakers.jpg",
     "nike air max sc sneakers lifestyle", {"Upper": "Leather & Mesh", "Cushioning": "Air Max Unit", "Sole": "Rubber", "Warranty": "90 Days"}),
]

# ---------------------------------------------------------------------------
# BAGS & LUGGAGE
# ---------------------------------------------------------------------------
BAGS = [
    ("Lavie Women's Quilted Satchel Handbag", "Lavie", "Handbags", 3490, 1745, "lavie_handbag.jpg",
     "lavie handbag satchel quilted women", {"Material": "Vegan Leather", "Compartments": "2 Main + 1 Zip", "Strap": "Detachable Sling", "Warranty": "6 Months"}),
    ("Baggit Women's Textured Tote Shoulder Bag", "Baggit", "Handbags", 2799, 1399, "lavie_handbag.jpg",
     "baggit tote handbag shoulder women", {"Material": "Synthetic", "Capacity": "12L", "Closure": "Zip", "Warranty": "6 Months"}),
    ("Hidesign Women's Genuine Leather Sling Bag", "Hidesign", "Handbags", 5995, 4196, "lavie_handbag.jpg",
     "hidesign sling bag leather women", {"Material": "Full Grain Leather", "Compartments": "1 Main + 1 Slip", "Strap": "Adjustable", "Warranty": "1 Year"}),
    ("Caprese Women's Structured Crossbody Bag", "Caprese", "Handbags", 3299, 1649, "lavie_handbag.jpg",
     "caprese crossbody bag women structured", {"Material": "PU Leather", "Closure": "Flap Magnetic", "Strap": "Chain Sling", "Warranty": "6 Months"}),
    ("Lavie Women's Mini Bucket Bag with Drawstring", "Lavie", "Handbags", 2290, 1145, "lavie_handbag.jpg",
     "lavie bucket bag mini drawstring", {"Material": "Vegan Leather", "Capacity": "5L", "Closure": "Drawstring", "Warranty": "6 Months"}),
    ("Skybags Brat 46L Casual Laptop Backpack", "Skybags", "Backpacks", 2200, 999, "teal_backpack.jpg",
     "skybags backpack laptop brat casual", {"Capacity": "46L", "Laptop Sleeve": "Up to 15.6in", "Material": "Polyester", "Warranty": "3 Years"}),
    ("Wildcraft 35L Water Resistant Trekking Backpack", "Wildcraft", "Backpacks", 2999, 1799, "teal_backpack.jpg",
     "wildcraft backpack trekking water resistant", {"Capacity": "35L", "Material": "Ripstop Polyester", "Rain Cover": "Included", "Warranty": "1 Year"}),
    ("American Tourister 32L Daily Laptop Backpack", "American Tourister", "Backpacks", 2450, 1225, "teal_backpack.jpg",
     "american tourister backpack laptop daily", {"Capacity": "32L", "Laptop Sleeve": "Up to 15.6in", "Material": "Polyester", "Warranty": "3 Years"}),
    ("Safari 30L Anti-Theft Office Laptop Backpack", "Safari", "Backpacks", 2799, 1259, "teal_backpack.jpg",
     "safari backpack anti theft office laptop", {"Capacity": "30L", "Security": "Hidden Anti-Theft Pocket", "USB Port": "Yes", "Warranty": "3 Years"}),
    ("Puma Unisex Training Gym Duffel Bag 25L", "Puma", "Backpacks", 2499, 1249, "teal_backpack.jpg",
     "puma duffel gym bag training", {"Capacity": "25L", "Material": "Polyester", "Shoe Compartment": "Yes", "Warranty": "90 Days"}),
    ("VIP Nexa 4-Wheel Hard Trolley Suitcase 65cm", "VIP", "Luggage", 7500, 3750, "teal_backpack.jpg",
     "vip suitcase trolley luggage hard", {"Size": "65cm Medium", "Wheels": "4 Spinner", "Lock": "Number Lock", "Warranty": "5 Years"}),
    ("American Tourister Polycarbonate Cabin Trolley 55cm", "American Tourister", "Luggage", 9500, 5225, "teal_backpack.jpg",
     "american tourister cabin trolley luggage", {"Size": "55cm Cabin", "Shell": "Polycarbonate", "Lock": "TSA Approved", "Warranty": "3 Years"}),
    ("Safari Pentagon Set of 3 Hard Trolley Bags", "Safari", "Luggage", 15999, 6399, "teal_backpack.jpg",
     "safari trolley set luggage hard 3", {"Set": "55 + 66 + 77cm", "Wheels": "8 Spinner", "Shell": "Polypropylene", "Warranty": "5 Years"}),
    ("Skybags Rubik 4-Wheel Soft Trolley 68cm", "Skybags", "Luggage", 6600, 2970, "teal_backpack.jpg",
     "skybags trolley soft luggage rubik", {"Size": "68cm Large", "Shell": "Soft Polyester", "Wheels": "4 Spinner", "Warranty": "3 Years"}),
    ("Wildcraft 55L Rucksack Travel Duffel Bag", "Wildcraft", "Luggage", 3499, 2099, "teal_backpack.jpg",
     "wildcraft rucksack duffel travel bag", {"Capacity": "55L", "Material": "Polyester", "Straps": "Padded Shoulder", "Warranty": "1 Year"}),
    ("Hidesign Men's Leather Laptop Messenger Bag", "Hidesign", "Backpacks", 8995, 6296, "lavie_handbag.jpg",
     "hidesign messenger bag leather laptop men", {"Material": "Vegetable Tanned Leather", "Laptop": "Up to 14in", "Closure": "Buckle Flap", "Warranty": "1 Year"}),
    ("Tommy Hilfiger Unisex Canvas Backpack 24L", "Tommy Hilfiger", "Backpacks", 5999, 3599, "teal_backpack.jpg",
     "tommy hilfiger backpack canvas unisex", {"Capacity": "24L", "Material": "Cotton Canvas", "Laptop Sleeve": "Up to 14in", "Warranty": "1 Year"}),
    ("Baggit Women's Foldable Travel Duffle", "Baggit", "Luggage", 2199, 1099, "teal_backpack.jpg",
     "baggit duffle travel foldable women", {"Capacity": "28L", "Material": "Synthetic", "Foldable": "Yes", "Warranty": "6 Months"}),
    ("Amazon Basics Unisex Everyday Backpack 20L", "Amazon Basics", "Backpacks", 1499, 749, "teal_backpack.jpg",
     "amazon basics backpack everyday budget", {"Capacity": "20L", "Material": "Polyester", "Laptop Sleeve": "Up to 14in", "Warranty": "1 Year"}),
    ("Caprese Women's Laptop Handbag with Trolley Sleeve", "Caprese", "Handbags", 4499, 2249, "lavie_handbag.jpg",
     "caprese laptop handbag women trolley", {"Material": "PU Leather", "Laptop": "Up to 14in", "Trolley Sleeve": "Yes", "Warranty": "6 Months"}),
]

# ---------------------------------------------------------------------------
# BEAUTY  (subcategories: Skincare, Makeup, Haircare, Fragrances, Bath & Body)
# ---------------------------------------------------------------------------
BEAUTY = [
    ("10% Niacinamide & Zinc Clarifying Face Serum 30ml", "Minimalist", "Skincare", 799, 599, "beauty_niacinamide_serum.jpg",
     "niacinamide serum face skincare zinc", {"Volume": "30ml", "Key Actives": "10% Niacinamide, 1% Zinc", "Skin Type": "Oily & Acne Prone", "Fragrance": "Free"}),
    ("Ceramide & Hyaluronic Barrier Repair Moisturiser 50g", "Dot & Key", "Skincare", 645, 484, "beauty_ceramide_cream.png",
     "ceramide moisturiser cream skincare barrier", {"Volume": "50g", "Key Actives": "Ceramides, Hyaluronic Acid", "Skin Type": "All / Dry", "Texture": "Gel Cream"}),
    ("Ultralight Aqua Sunscreen Gel SPF 50 PA++++ 50g", "Minimalist", "Skincare", 449, 359, "beauty_sunscreen_gel.png",
     "sunscreen spf 50 gel skincare aqua", {"Volume": "50g", "SPF": "50 PA++++", "Finish": "Matte No White Cast", "Skin Type": "All"}),
    ("Vitamin C Brightening Foaming Face Wash 100ml", "Plum", "Skincare", 390, 312, "beauty_vitamin_c_facewash.png",
     "vitamin c face wash foaming skincare", {"Volume": "100ml", "Key Actives": "Vitamin C, Mandarin", "Skin Type": "Dull & Uneven", "pH": "5.5"}),
    ("Rose Water Hydrating Face Mist Toner 200ml", "Kama Ayurveda", "Skincare", 850, 680, "beauty_rosewater_mist.jpg",
     "rose water face mist toner skincare", {"Volume": "200ml", "Key Actives": "Pure Rose Distillate", "Skin Type": "All", "Alcohol": "Free"}),
    ("2% Salicylic Acid Anti-Acne Face Serum 30ml", "The Derma Co", "Skincare", 599, 449, "beauty_niacinamide_serum.jpg",
     "salicylic acid serum acne skincare", {"Volume": "30ml", "Key Actives": "2% Salicylic Acid", "Skin Type": "Acne Prone", "Use": "PM Only"}),
    ("Retinol 0.3% Youth Renewal Night Serum 30ml", "Minimalist", "Skincare", 899, 719, "beauty_niacinamide_serum.jpg",
     "retinol serum night anti aging skincare", {"Volume": "30ml", "Key Actives": "0.3% Retinol, Squalane", "Skin Type": "Mature", "Use": "Night Only"}),
    ("Matte Liquid Velvet Lipstick - Ruby Rush", "Sugar Cosmetics", "Makeup", 799, 599, "beauty_matte_lipstick.jpg",
     "lipstick matte liquid velvet makeup", {"Shade": "Ruby Rush", "Finish": "Transfer-Proof Matte", "Wear Time": "12 Hours", "Volume": "4.5ml"}),
    ("Complexion Care CC Cream SPF 30 - Medium 30ml", "Lakme", "Makeup", 475, 356, "beauty_cc_cream.png",
     "cc cream complexion makeup spf", {"Shade": "Medium", "SPF": "30", "Coverage": "Light to Medium", "Volume": "30ml"}),
    ("Volumising Waterproof Curl Mascara Jet Black", "Maybelline", "Makeup", 599, 449, "beauty_mascara.jpg",
     "mascara volumising waterproof makeup", {"Shade": "Jet Black", "Formula": "Waterproof", "Brush": "Curved Curl", "Volume": "9.2ml"}),
    ("24H Matte Full Coverage Liquid Foundation 30ml", "Maybelline", "Makeup", 749, 561, "beauty_cc_cream.png",
     "foundation liquid matte makeup coverage", {"Coverage": "Full", "Finish": "Matte", "Wear Time": "24 Hours", "Shades": "12 Available"}),
    ("Baked Blush & Highlighter Duo Palette", "Sugar Cosmetics", "Makeup", 899, 674, "beauty_matte_lipstick.jpg",
     "blush highlighter palette makeup baked", {"Shades": "2 in 1 Duo", "Finish": "Satin Shimmer", "Buildable": "Yes", "Weight": "8g"}),
    ("Precision Liquid Eyeliner Pen Intense Black", "Nykaa Cosmetics", "Makeup", 399, 299, "beauty_mascara.jpg",
     "eyeliner liquid pen makeup precision", {"Shade": "Intense Black", "Tip": "0.5mm Felt", "Formula": "Smudge Proof", "Volume": "1.2ml"}),
    ("Red Onion Hair Growth Oil with Redensyl 100ml", "Wow Skin Science", "Haircare", 599, 419, "beauty_onion_hair_oil.png",
     "onion hair oil growth haircare redensyl", {"Volume": "100ml", "Key Actives": "Onion Seed Oil, Redensyl", "Hair Type": "Thinning", "Silicone": "Free"}),
    ("Argan Oil Hair Recovery Repair Serum 100ml", "Streax Professional", "Haircare", 499, 374, "beauty_argan_hair_serum.jpg",
     "argan oil hair serum repair haircare", {"Volume": "100ml", "Key Actives": "Moroccan Argan Oil", "Hair Type": "Dry & Frizzy", "Finish": "Non Greasy"}),
    ("Keratin Smooth Anti-Frizz Shampoo 340ml", "L'Oreal Paris", "Haircare", 725, 544, "beauty_argan_hair_serum.jpg",
     "keratin shampoo smooth anti frizz haircare", {"Volume": "340ml", "Key Actives": "Pro-Keratin", "Hair Type": "Frizzy", "Sulphate": "Low"}),
    ("Rosemary & Biotin Anti-Hairfall Shampoo 300ml", "Mamaearth", "Haircare", 449, 359, "beauty_onion_hair_oil.png",
     "rosemary biotin shampoo hairfall haircare", {"Volume": "300ml", "Key Actives": "Rosemary, Biotin", "Hair Type": "Weak & Falling", "Sulphate": "Free"}),
    ("Deep Repair Hair Mask with Shea Butter 200g", "Dot & Key", "Haircare", 695, 521, "beauty_argan_hair_serum.jpg",
     "hair mask repair shea butter haircare", {"Volume": "200g", "Key Actives": "Shea Butter, Amino Acids", "Hair Type": "Damaged", "Use": "Twice Weekly"}),
    ("Royal Oud Long Lasting Eau De Parfum 100ml", "Ajmal", "Fragrances", 2999, 2099, "beauty_oud_perfume.jpg",
     "oud perfume eau de parfum fragrance", {"Volume": "100ml", "Notes": "Oud, Amber, Saffron", "Longevity": "10-12 Hours", "Type": "Unisex EDP"}),
    ("Skinn Raw Men's Eau De Parfum 100ml", "Titan Skinn", "Fragrances", 2495, 1746, "beauty_oud_perfume.jpg",
     "skinn perfume men eau de parfum fragrance", {"Volume": "100ml", "Notes": "Citrus, Leather, Vetiver", "Longevity": "8 Hours", "Type": "Men's EDP"}),
    ("Bella Vita Woman Luxury Perfume Gift Set 4x20ml", "Bella Vita", "Fragrances", 1499, 899, "beauty_oud_perfume.jpg",
     "bella vita perfume gift set women fragrance", {"Set": "4 x 20ml", "Notes": "Floral, Fruity, Musk", "Type": "Women's EDP", "Travel Friendly": "Yes"}),
    ("Wild Stone Ultra Sensual Body Perfume Spray 120ml", "Wild Stone", "Fragrances", 399, 279, "beauty_oud_perfume.jpg",
     "wild stone body spray perfume deodorant", {"Volume": "120ml", "Notes": "Woody Musk", "Longevity": "6 Hours", "Gas": "No Gas Formula"}),
    ("Japanese Cherry Blossom Body Wash 250ml", "Plum BodyLovin", "Bath & Body", 445, 356, "beauty_cherry_bodywash.png",
     "cherry blossom body wash bath shower gel", {"Volume": "250ml", "Fragrance": "Cherry Blossom", "Sulphate": "Free", "Skin Type": "All"}),
    ("Ubtan Exfoliating Body Scrub with Walnut 200g", "Mamaearth", "Bath & Body", 499, 374, "beauty_cherry_bodywash.png",
     "ubtan body scrub exfoliating bath walnut", {"Volume": "200g", "Key Actives": "Turmeric, Saffron, Walnut", "Use": "Twice Weekly", "Paraben": "Free"}),
    ("Shea Butter Intense Nourishing Body Lotion 400ml", "Nivea", "Bath & Body", 499, 374, "beauty_ceramide_cream.png",
     "shea butter body lotion nourishing bath", {"Volume": "400ml", "Key Actives": "Shea Butter, Vitamin E", "Skin Type": "Very Dry", "Absorption": "Fast"}),
]
