"""
Home, furniture, appliance, sports and books catalogue data for ``seed_marketplace``.

Same tuple shape as ``_marketplace_tech``:
    (title, brand, subcategory, base_price, discount_price, image, tags, specs)

Subcategory names are deliberately verbatim matches for the filter chip ids in
``frontend/src/pages/HomeKitchenPage.jsx`` (``Furniture``, ``Cookware``,
``Home Decor``, ``Bedding``, ``Appliances``) so the storefront filters resolve
against real rows instead of the bundled literals.
"""

# ---------------------------------------------------------------------------
# HOME & KITCHEN  (Cookware / Home Decor / Bedding)
# ---------------------------------------------------------------------------
HOME_KITCHEN = [
    ("Prestige Svachh 5L Outer Lid Aluminium Pressure Cooker", "Prestige", "Cookware", 3450, 2199, "hk_pressure_cooker.jpg",
     "pressure cooker prestige aluminium cookware 5l", {"Capacity": "5 Litre", "Material": "Virgin Aluminium", "Lid": "Outer Lid Svachh", "Warranty": "5 Years"}),
    ("Hawkins Contura Hard Anodised 3L Pressure Cooker", "Hawkins", "Cookware", 2900, 2030, "pressure_cooker.jpg",
     "pressure cooker hawkins contura hard anodised cookware", {"Capacity": "3 Litre", "Material": "Hard Anodised", "Lid": "Inner Lid", "Warranty": "5 Years"}),
    ("Hawkins Futura 7-Piece Non-Stick Cookware Set", "Hawkins", "Cookware", 8999, 5399, "hk_cookware_set.jpg",
     "cookware set non stick kitchen 7 piece", {"Pieces": "7", "Coating": "Triple Layer Non-Stick", "Base": "Induction Compatible", "Warranty": "2 Years"}),
    ("Pigeon Stainless Steel Triply 5-Piece Cookware Set", "Pigeon", "Cookware", 6499, 3249, "hk_cookware_set.jpg",
     "cookware set stainless steel triply kitchen", {"Pieces": "5", "Material": "Triply Stainless Steel", "Base": "Induction Compatible", "Warranty": "3 Years"}),
    ("Borosil Glass Casserole Set of 3 with Lids", "Borosil", "Cookware", 2999, 1799, "hk_casserole_set.png",
     "casserole set glass borosil serving kitchen", {"Pieces": "3 with Lids", "Material": "Borosilicate Glass", "Oven Safe": "Up to 300C", "Warranty": "2 Years"}),
    ("Milton Thermosteel Insulated Casserole Set of 3", "Milton", "Cookware", 3499, 2099, "hk_casserole_set.png",
     "casserole set thermosteel insulated milton serving", {"Pieces": "3", "Material": "Stainless Steel", "Heat Retention": "Up to 4 Hours", "Warranty": "1 Year"}),
    ("Cello Opalware 27-Piece Ceramic Dinner Set", "Cello", "Cookware", 7999, 3999, "hk_ceramic_dinner_set.png",
     "dinner set ceramic opalware 27 piece dining", {"Pieces": "27", "Material": "Opalware", "Microwave Safe": "Yes", "Warranty": "1 Year"}),
    ("Larah by Borosil 19-Piece Opalware Dinner Set", "Borosil", "Cookware", 5999, 3599, "hk_ceramic_dinner_set.png",
     "dinner set opalware larah dining ceramic", {"Pieces": "19", "Material": "Opalware", "Dishwasher Safe": "Yes", "Warranty": "2 Years"}),
    ("Prestige Omega Deluxe Granite 24cm Non-Stick Kadai", "Prestige", "Cookware", 2299, 1379, "hk_cookware_set.jpg",
     "kadai non stick granite prestige cookware", {"Diameter": "24cm", "Coating": "Granite Non-Stick", "Base": "Induction Compatible", "Warranty": "2 Years"}),
    ("Vinod Stainless Steel Induction Base Tope Set of 3", "Vinod", "Cookware", 2799, 1679, "hk_cookware_set.jpg",
     "tope set stainless steel induction cookware", {"Pieces": "3", "Material": "Stainless Steel 304", "Base": "Induction Compatible", "Warranty": "1 Year"}),
    ("Nordic Wooden Floating Wall Shelves Set of 3", "UrbanHome", "Home Decor", 3499, 1749, "hk_wall_shelves.png",
     "wall shelves wooden floating decor storage", {"Pieces": "3", "Material": "Engineered Wood", "Load Capacity": "10kg each", "Finish": "Walnut"}),
    ("Brass Finish Dome Pendant Ceiling Lamp", "Homesake", "Home Decor", 4999, 2499, "hk_pendant_lamp.jpg",
     "pendant lamp ceiling brass decor lighting", {"Material": "Iron with Brass Finish", "Bulb": "E27 Holder", "Cord Length": "1m Adjustable", "Warranty": "1 Year"}),
    ("Industrial Black Metal Pendant Hanging Light", "Homesake", "Home Decor", 3999, 1999, "pendant_lamp.jpg",
     "pendant hanging light metal industrial decor lighting", {"Material": "Powder Coated Metal", "Bulb": "E27 Holder", "Style": "Industrial", "Warranty": "1 Year"}),
    ("Handcrafted Terracotta Hanging Diya Set of 6", "ExclusiveLane", "Home Decor", 1799, 899, "rakhi_hanging_lamps.png",
     "diya terracotta hanging festive decor set", {"Pieces": "6", "Material": "Terracotta", "Occasion": "Festive Decor", "Handmade": "Yes"}),
    ("Warm White LED Fairy String Lights 10m", "Wipro", "Home Decor", 999, 499, "rakhi_hanging_lamps.png",
     "string lights led fairy decor festive", {"Length": "10 Metre", "Colour": "Warm White", "Modes": "8 Lighting Modes", "Warranty": "1 Year"}),
    ("Framed Abstract Canvas Wall Art Set of 3", "ExclusiveLane", "Home Decor", 2999, 1499, "hk_wall_shelves.png",
     "wall art canvas framed decor abstract", {"Pieces": "3", "Frame": "Solid Wood", "Size": "12 x 16 inch each", "Ready to Hang": "Yes"}),
    ("Ceramic Table Vase with Dried Pampas Grass", "ExclusiveLane", "Home Decor", 1699, 849, "hk_ceramic_dinner_set.png",
     "vase ceramic pampas decor table", {"Material": "Glazed Ceramic", "Height": "26cm", "Includes": "Dried Pampas", "Care": "Wipe Clean"}),
    ("Handwoven Jute Area Rug 4x6 Feet", "Homesake", "Home Decor", 4499, 2249, "hk_wall_shelves.png",
     "rug jute handwoven area decor carpet", {"Size": "4 x 6 Feet", "Material": "Natural Jute", "Backing": "Anti-Skid", "Care": "Vacuum Clean"}),
    ("Bombay Dyeing 210 TC Cotton Double Bedsheet with 2 Pillow Covers", "Bombay Dyeing", "Bedding", 2499, 1249, "hk_cotton_bedsheet.png",
     "bedsheet cotton double bedding pillow covers", {"Size": "Double 90 x 100 inch", "Thread Count": "210 TC", "Material": "100% Cotton", "Includes": "2 Pillow Covers"}),
    ("Spaces 300 TC Sateen Weave King Bedsheet Set", "Spaces", "Bedding", 3999, 2399, "hk_cotton_bedsheet.png",
     "bedsheet sateen king bedding 300 tc", {"Size": "King 108 x 108 inch", "Thread Count": "300 TC", "Weave": "Sateen", "Includes": "2 Pillow Covers"}),
    ("Sleepwell Orthopaedic Memory Foam Pillow Pack of 2", "Sleepwell", "Bedding", 2999, 1499, "hk_memory_pillow.jpg",
     "pillow memory foam orthopaedic bedding pack", {"Pack": "2 Pillows", "Fill": "Visco Memory Foam", "Cover": "Removable Knit", "Warranty": "3 Years"}),
    ("Wakefit Cervical Contour Memory Foam Pillow", "Wakefit", "Bedding", 1999, 1199, "hk_memory_pillow.jpg",
     "pillow cervical contour memory foam bedding", {"Type": "Cervical Contour", "Fill": "Memory Foam", "Cover": "Bamboo Fabric", "Warranty": "3 Years"}),
    ("Trident Microfibre Reversible Double Comforter", "Trident", "Bedding", 4499, 2249, "hk_cotton_bedsheet.png",
     "comforter microfibre reversible double bedding quilt", {"Size": "Double 220 x 240cm", "Fill": "Microfibre 300 GSM", "Reversible": "Yes", "Care": "Machine Wash"}),
    ("Portico Waffle Weave Cotton Bath Towel Set of 4", "Portico", "Bedding", 2799, 1399, "hk_cotton_bedsheet.png",
     "towel set cotton bath waffle bedding", {"Pieces": "4", "GSM": "500", "Material": "100% Combed Cotton", "Care": "Machine Wash"}),
    ("Wakefit Water Resistant Double Mattress Protector", "Wakefit", "Bedding", 1799, 899, "hk_cotton_bedsheet.png",
     "mattress protector water resistant double bedding", {"Size": "Double 78 x 60 inch", "Feature": "Water Resistant", "Fit": "Elastic Fitted", "Warranty": "1 Year"}),
]

# ---------------------------------------------------------------------------
# CHAIRS & FURNITURE  (single subcategory "Furniture" to match the page filter)
# ---------------------------------------------------------------------------
FURNITURE = [
    ("Modern Ergonomic Velvet Accent Armchair", "UrbanHome", "Furniture", 11999, 6999, "accent_chair.jpg",
     "accent armchair velvet ergonomic furniture chair", {"Material": "Solid Wood & Velvet", "Seat Height": "45cm", "Load Capacity": "120kg", "Warranty": "1 Year"}),
    ("Emerald Green Tufted Velvet Accent Chair", "UrbanHome", "Furniture", 14999, 8999, "emerald_accent_chair.jpg",
     "accent chair emerald velvet tufted furniture", {"Material": "Velvet & Beech Wood", "Seat Height": "46cm", "Load Capacity": "120kg", "Warranty": "1 Year"}),
    ("Beige Boucle Upholstered Lounge Chair", "Nilkamal", "Furniture", 13499, 7499, "beige_boucle_chair.jpg",
     "boucle lounge chair beige upholstered furniture", {"Material": "Boucle Fabric", "Frame": "Metal Legs", "Load Capacity": "110kg", "Warranty": "1 Year"}),
    ("Brown Genuine Leather Wingback Armchair", "Durian", "Furniture", 27999, 17999, "brown_leather_armchair.jpg",
     "leather armchair wingback brown furniture", {"Material": "Genuine Leather", "Frame": "Kiln Dried Hardwood", "Load Capacity": "130kg", "Warranty": "3 Years"}),
    ("Mid-Century Walnut Frame Fabric Armchair", "Wakefit", "Furniture", 16999, 10199, "midcentury_armchair.jpg",
     "midcentury armchair walnut fabric furniture", {"Material": "Solid Sheesham & Fabric", "Style": "Mid-Century", "Load Capacity": "120kg", "Warranty": "3 Years"}),
    ("Single Seater Manual Recliner Sofa Chair", "Durian", "Furniture", 34999, 21999, "lounge_recliner.jpg",
     "recliner sofa single seater furniture lounge", {"Mechanism": "Manual Pushback", "Upholstery": "Leatherette", "Recline": "150 Degree", "Warranty": "3 Years"}),
    ("Fabric Lounge Chair with Solid Wood Legs", "Nilkamal", "Furniture", 12499, 6999, "lounge_chair.jpg",
     "lounge chair fabric wood legs furniture", {"Material": "Polyester Fabric", "Frame": "Rubber Wood", "Load Capacity": "110kg", "Warranty": "1 Year"}),
    ("Scandinavian Accent Armchair with Cushion", "UrbanHome", "Furniture", 15999, 9599, "hk_accent_armchair.jpg",
     "accent armchair scandinavian cushion furniture", {"Material": "Linen Blend", "Frame": "Solid Ash", "Load Capacity": "115kg", "Warranty": "2 Years"}),
    ("Deep Seat Chesterfield Lounge Chair", "Durian", "Furniture", 29999, 18999, "hk_lounge_chair.jpg",
     "chesterfield lounge chair deep seat furniture", {"Material": "Velvet Upholstery", "Frame": "Hardwood", "Style": "Chesterfield", "Warranty": "3 Years"}),
    ("Wakefit Sheesham Wood 4-Seater Dining Table Set", "Wakefit", "Furniture", 44999, 28999, "midcentury_armchair.jpg",
     "dining table set sheesham 4 seater furniture", {"Seating": "4 Seater", "Material": "Solid Sheesham", "Finish": "Honey Teak", "Warranty": "3 Years"}),
    ("Nilkamal 3-Seater Fabric Sofa with Cushions", "Nilkamal", "Furniture", 39999, 23999, "lounge_chair.jpg",
     "sofa 3 seater fabric cushions furniture", {"Seating": "3 Seater", "Upholstery": "Premium Fabric", "Foam": "High Density", "Warranty": "2 Years"}),
    ("Engineered Wood Study Table with Drawer", "Wakefit", "Furniture", 12999, 7799, "hk_wall_shelves.png",
     "study table desk wood drawer furniture", {"Material": "Engineered Wood", "Size": "110 x 55cm", "Storage": "1 Drawer + Shelf", "Warranty": "1 Year"}),
    ("5-Tier Ladder Bookshelf in Walnut Finish", "UrbanHome", "Furniture", 9999, 5999, "hk_wall_shelves.png",
     "bookshelf ladder 5 tier walnut furniture storage", {"Tiers": "5", "Material": "Engineered Wood", "Finish": "Walnut", "Warranty": "1 Year"}),
    ("Solid Wood Bedside Nightstand with Drawer", "Durian", "Furniture", 8999, 5399, "midcentury_armchair.jpg",
     "nightstand bedside table drawer furniture", {"Material": "Solid Mango Wood", "Size": "45 x 40cm", "Storage": "1 Drawer + Open Shelf", "Warranty": "2 Years"}),
    ("Nesting Coffee Table Set of 2 with Metal Frame", "Homesake", "Furniture", 11499, 6899, "hk_wall_shelves.png",
     "coffee table nesting set metal furniture", {"Pieces": "2", "Top": "Engineered Wood", "Frame": "Powder Coated Metal", "Warranty": "1 Year"}),
    ("Foldable Wooden Shoe Rack 4-Tier", "Nilkamal", "Furniture", 5999, 2999, "hk_wall_shelves.png",
     "shoe rack foldable wooden 4 tier furniture storage", {"Tiers": "4", "Capacity": "12 Pairs", "Material": "Engineered Wood", "Warranty": "1 Year"}),
    ("Wakefit Orthopaedic Memory Foam Queen Mattress 6 inch", "Wakefit", "Furniture", 24999, 14999, "hk_memory_pillow.jpg",
     "mattress memory foam queen orthopaedic furniture", {"Size": "Queen 78 x 60 inch", "Thickness": "6 inch", "Firmness": "Medium Firm", "Warranty": "10 Years"}),
    ("Sleepwell Dual Comfort Double Mattress 5 inch", "Sleepwell", "Furniture", 18999, 11399, "hk_memory_pillow.jpg",
     "mattress dual comfort double sleepwell furniture", {"Size": "Double 72 x 48 inch", "Thickness": "5 inch", "Firmness": "Reversible Soft/Hard", "Warranty": "5 Years"}),
    ("Ergonomic Mesh Back Revolving Office Chair", "Nilkamal", "Furniture", 13999, 7699, "accent_chair.jpg",
     "office chair ergonomic mesh revolving furniture", {"Back": "Breathable Mesh", "Adjust": "Height & Tilt", "Load Capacity": "110kg", "Warranty": "1 Year"}),
    ("Wooden Bar Stool Set of 2 with Footrest", "Homesake", "Furniture", 10999, 6599, "midcentury_armchair.jpg",
     "bar stool set wooden footrest furniture", {"Pieces": "2", "Seat Height": "65cm", "Material": "Solid Rubber Wood", "Warranty": "1 Year"}),
    ("2-Door Engineered Wood Wardrobe with Mirror", "Durian", "Furniture", 32999, 19799, "hk_wall_shelves.png",
     "wardrobe 2 door wood mirror furniture storage", {"Doors": "2", "Material": "Engineered Wood", "Features": "Mirror + Drawer", "Warranty": "2 Years"}),
    ("Rattan Weave Balcony Chair & Table Set", "Homesake", "Furniture", 17999, 10799, "beige_boucle_chair.jpg",
     "balcony chair table set rattan outdoor furniture", {"Set": "2 Chairs + 1 Table", "Material": "Synthetic Rattan", "Weather Resistant": "Yes", "Warranty": "1 Year"}),
]

# ---------------------------------------------------------------------------
# APPLIANCES  (single subcategory "Appliances" to match the page filter)
# ---------------------------------------------------------------------------
APPLIANCES = [
    ("Philips Digital Airfryer HD9252 4.1L", "Philips", "Appliances", 12995, 8446, "hk_air_fryer.jpg",
     "air fryer philips digital appliance kitchen", {"Capacity": "4.1 Litre", "Power": "1400W", "Technology": "Rapid Air", "Warranty": "2 Years"}),
    ("Havells Prolife Digital Air Fryer 5L", "Havells", "Appliances", 9995, 5497, "hk_air_fryer.jpg",
     "air fryer havells digital 5l appliance", {"Capacity": "5 Litre", "Power": "1500W", "Presets": "8 Preset Menus", "Warranty": "2 Years"}),
    ("Philips HL7756 Mixer Grinder 750W with 3 Jars", "Philips", "Appliances", 6495, 4222, "hk_mixer_grinder.jpg",
     "mixer grinder philips 750w jars appliance kitchen", {"Power": "750W", "Jars": "3 Stainless Steel", "Speed": "3 Speed + Pulse", "Warranty": "2 Years"}),
    ("Bajaj Rex 500W Mixer Grinder with 3 Jars", "Bajaj", "Appliances", 3799, 2279, "hk_mixer_grinder.jpg",
     "mixer grinder bajaj rex 500w appliance kitchen", {"Power": "500W", "Jars": "3", "Speed": "3 Speed", "Warranty": "2 Years"}),
    ("Preethi Zodiac 750W Mixer Grinder with 5 Jars", "Preethi", "Appliances", 9450, 6615, "hk_mixer_grinder.jpg",
     "mixer grinder preethi zodiac 750w jars appliance", {"Power": "750W", "Jars": "5 including Master Chef", "Motor": "Vega W5", "Warranty": "5 Years Motor"}),
    ("Prestige Iris 750W Juicer Mixer Grinder", "Prestige", "Appliances", 5495, 3297, "hk_mixer_grinder.jpg",
     "juicer mixer grinder prestige appliance kitchen", {"Power": "750W", "Jars": "4 + Juicer", "Overload Protection": "Yes", "Warranty": "2 Years"}),
    ("Morphy Richards 1000W Induction Cooktop", "Morphy Richards", "Appliances", 4295, 2577, "hk_air_fryer.jpg",
     "induction cooktop morphy richards appliance kitchen", {"Power": "1000W", "Presets": "8 Indian Menus", "Panel": "Touch Keypad", "Warranty": "1 Year"}),
    ("Pigeon Cruise 1800W Induction Cooktop", "Pigeon", "Appliances", 3295, 1647, "hk_air_fryer.jpg",
     "induction cooktop pigeon 1800w appliance kitchen", {"Power": "1800W", "Presets": "7 Menus", "Panel": "Push Button", "Warranty": "1 Year"}),
    ("Butterfly Rapid 750W 2-Slice Sandwich Toaster", "Butterfly", "Appliances", 2599, 1559, "hk_air_fryer.jpg",
     "sandwich toaster butterfly grill appliance kitchen", {"Power": "750W", "Slices": "2", "Plates": "Non-Stick Grill", "Warranty": "1 Year"}),
    ("Prestige 1.5L Stainless Steel Electric Kettle", "Prestige", "Appliances", 2295, 1147, "hk_air_fryer.jpg",
     "electric kettle prestige stainless steel appliance", {"Capacity": "1.5 Litre", "Power": "1500W", "Body": "Stainless Steel", "Warranty": "2 Years"}),
    ("Bajaj Majesty 2L Electric Rice Cooker", "Bajaj", "Appliances", 3199, 1919, "hk_air_fryer.jpg",
     "rice cooker bajaj electric appliance kitchen", {"Capacity": "2 Litre", "Power": "700W", "Pan": "Anodised Inner Pan", "Warranty": "2 Years"}),
    ("Havells Aqua Plus 8L Instant Water Heater", "Havells", "Appliances", 8990, 5394, "hk_air_fryer.jpg",
     "water heater havells geyser instant appliance", {"Capacity": "8 Litre", "Power": "3000W", "Rating": "5 Star", "Warranty": "7 Years Tank"}),
    ("Wipro Garnet 1200mm BLDC Ceiling Fan", "Wipro", "Appliances", 4499, 3149, "hk_pendant_lamp.jpg",
     "ceiling fan bldc wipro appliance energy saving", {"Sweep": "1200mm", "Power": "35W BLDC", "Remote": "Included", "Warranty": "3 Years"}),
    ("Havells Swing 400mm High Speed Table Fan", "Havells", "Appliances", 3290, 1974, "hk_pendant_lamp.jpg",
     "table fan havells high speed appliance", {"Sweep": "400mm", "Speed": "2200 RPM", "Blades": "3 Aerodynamic", "Warranty": "2 Years"}),
    ("Eureka Forbes 1400W Wet & Dry Vacuum Cleaner", "Eureka Forbes", "Appliances", 9999, 5999, "hk_air_fryer.jpg",
     "vacuum cleaner wet dry eureka forbes appliance", {"Power": "1400W", "Tank": "20 Litre", "Blower Function": "Yes", "Warranty": "1 Year"}),
    ("Philips 2400W Steam Iron with Ceramic Soleplate", "Philips", "Appliances", 3495, 2097, "hk_air_fryer.jpg",
     "steam iron philips ceramic soleplate appliance", {"Power": "2400W", "Steam Boost": "150g", "Soleplate": "SteamGlide Ceramic", "Warranty": "2 Years"}),
    ("Bajaj 20L Solo Microwave Oven", "Bajaj", "Appliances", 7990, 4794, "hk_air_fryer.jpg",
     "microwave oven bajaj solo 20l appliance kitchen", {"Capacity": "20 Litre", "Type": "Solo", "Power Levels": "5", "Warranty": "1 Year"}),
    ("Morphy Richards 25L Convection Microwave Oven", "Morphy Richards", "Appliances", 15999, 9599, "hk_air_fryer.jpg",
     "microwave oven convection morphy richards appliance", {"Capacity": "25 Litre", "Type": "Convection", "Presets": "200 Auto Cook", "Warranty": "1 Year"}),
    ("Kent Grand Plus 8L RO + UV Water Purifier", "Kent", "Appliances", 20500, 15375, "hk_air_fryer.jpg",
     "water purifier kent ro uv appliance", {"Capacity": "8 Litre", "Purification": "RO + UV + UF + TDS", "Flow Rate": "20 L/hr", "Warranty": "1 Year + 3 Free Services"}),
    ("Prestige 2-Burner Toughened Glass Gas Stove", "Prestige", "Appliances", 5695, 3417, "hk_cookware_set.jpg",
     "gas stove prestige 2 burner glass appliance kitchen", {"Burners": "2", "Top": "Toughened Glass", "Ignition": "Manual", "Warranty": "2 Years"}),
    ("Butterfly Smart 3-Burner Stainless Steel Gas Stove", "Butterfly", "Appliances", 6499, 3899, "hk_cookware_set.jpg",
     "gas stove butterfly 3 burner steel appliance", {"Burners": "3", "Top": "Stainless Steel", "Ignition": "Manual", "Warranty": "2 Years"}),
    ("Havells 1.2L Hand Blender with Chopper Attachment", "Havells", "Appliances", 3999, 2399, "hk_mixer_grinder.jpg",
     "hand blender havells chopper appliance kitchen", {"Power": "300W", "Attachments": "Chopper + Whisker", "Speed": "Variable", "Warranty": "2 Years"}),
]

# ---------------------------------------------------------------------------
# SPORTS & FITNESS
# ---------------------------------------------------------------------------
SPORTS = [
    ("Nivia Storm Football Size 5", "Nivia", "Outdoor Sports", 1299, 649, "puma_shoes.jpg",
     "football nivia storm sports outdoor", {"Size": "5", "Material": "Rubberised", "Surface": "All Surface", "Warranty": "3 Months"}),
    ("Cosco Cricket Tennis Ball Pack of 6", "Cosco", "Outdoor Sports", 899, 449, "puma_shoes.jpg",
     "cricket tennis ball cosco pack sports", {"Pack": "6 Balls", "Type": "Heavy Tennis", "Use": "Practice & Match", "Warranty": "None"}),
    ("Yonex GR 303 Aluminium Badminton Racquet Set of 2", "Yonex", "Outdoor Sports", 2290, 1374, "puma_shoes.jpg",
     "badminton racquet yonex aluminium sports set", {"Pack": "2 Racquets", "Frame": "Aluminium", "Grip": "G4", "Warranty": "6 Months"}),
    ("Cosco Volleyball Super 270 Size 4", "Cosco", "Outdoor Sports", 1499, 899, "puma_shoes.jpg",
     "volleyball cosco super sports outdoor", {"Size": "4", "Material": "Rubber Moulded", "Panels": "18", "Warranty": "3 Months"}),
    ("Nivia Kross World Basketball Size 7", "Nivia", "Outdoor Sports", 1799, 1079, "puma_shoes.jpg",
     "basketball nivia kross sports outdoor", {"Size": "7", "Material": "Rubber", "Surface": "Indoor & Outdoor", "Warranty": "3 Months"}),
    ("Boldfit 6mm Anti-Skid Yoga Mat with Carry Strap", "Boldfit", "Fitness", 1499, 749, "teal_backpack.jpg",
     "yoga mat boldfit anti skid fitness exercise", {"Thickness": "6mm", "Material": "TPE", "Size": "183 x 61cm", "Includes": "Carry Strap"}),
    ("Kore PVC Dumbbell Set 2 x 5kg with Grip", "Kore", "Fitness", 2499, 1499, "teal_backpack.jpg",
     "dumbbell set kore pvc fitness gym weights", {"Weight": "2 x 5kg", "Material": "PVC Coated", "Grip": "Textured Handle", "Warranty": "1 Year"}),
    ("Kore Vinyl Adjustable Dumbbell Set 20kg", "Kore", "Fitness", 4999, 2999, "teal_backpack.jpg",
     "adjustable dumbbell set kore 20kg fitness gym", {"Weight": "20kg Total", "Type": "Adjustable Plates", "Rod": "Chrome Spinlock", "Warranty": "1 Year"}),
    ("Boldfit Resistance Loop Bands Set of 5", "Boldfit", "Fitness", 999, 449, "teal_backpack.jpg",
     "resistance bands boldfit loop fitness workout", {"Pack": "5 Bands", "Resistance": "5 to 40 lbs", "Material": "Natural Latex", "Includes": "Carry Pouch"}),
    ("Boldfit Skipping Rope with Ball Bearing", "Boldfit", "Fitness", 599, 299, "teal_backpack.jpg",
     "skipping rope boldfit jump fitness cardio", {"Length": "3m Adjustable", "Bearing": "Ball Bearing", "Handle": "Anti-Slip Foam", "Warranty": "6 Months"}),
    ("Kore Foam Roller for Muscle Recovery 33cm", "Kore", "Fitness", 1299, 649, "teal_backpack.jpg",
     "foam roller kore muscle recovery fitness", {"Length": "33cm", "Material": "High Density EVA", "Use": "Myofascial Release", "Warranty": "6 Months"}),
    ("Boldfit Adjustable Ab Roller Wheel", "Boldfit", "Fitness", 1199, 599, "teal_backpack.jpg",
     "ab roller wheel boldfit core fitness", {"Wheels": "Dual Wheel", "Handle": "Foam Grip", "Load": "Up to 120kg", "Warranty": "6 Months"}),
    ("Kore 65cm Anti-Burst Gym Exercise Ball with Pump", "Kore", "Fitness", 1499, 749, "teal_backpack.jpg",
     "exercise ball gym kore fitness stability", {"Diameter": "65cm", "Material": "Anti-Burst PVC", "Load": "300kg", "Includes": "Hand Pump"}),
    ("Boldfit Stainless Steel Gym Shaker Bottle 700ml", "Boldfit", "Fitness", 899, 449, "teal_backpack.jpg",
     "shaker bottle boldfit gym fitness steel", {"Capacity": "700ml", "Material": "Stainless Steel", "Leak Proof": "Yes", "Warranty": "6 Months"}),
    ("Puma Unisex Training Gym Gloves", "Puma", "Fitness", 1799, 899, "teal_backpack.jpg",
     "gym gloves puma training fitness workout", {"Material": "Synthetic Leather", "Wrist": "Velcro Strap", "Padding": "Gel Palm", "Warranty": "90 Days"}),
    ("Kore Digital Weighing Scale with LED Display", "Kore", "Fitness", 1999, 999, "teal_backpack.jpg",
     "weighing scale kore digital fitness health", {"Capacity": "180kg", "Display": "Blue LED", "Platform": "Tempered Glass", "Warranty": "1 Year"}),
]

# ---------------------------------------------------------------------------
# BOOKS & MORE
#
# NOTE: no book photography ships with this repo, so these rows deliberately
# reuse a neutral shelf image. Swap in real covers when assets are available.
# ---------------------------------------------------------------------------
BOOKS = [
    ("Atomic Habits by James Clear (Paperback)", "Penguin", "Non Fiction", 799, 399, "hk_wall_shelves.png",
     "atomic habits book non fiction self help", {"Author": "James Clear", "Format": "Paperback", "Pages": "320", "Language": "English"}),
    ("Ikigai: The Japanese Secret to a Long Happy Life", "Penguin", "Non Fiction", 599, 299, "hk_wall_shelves.png",
     "ikigai book non fiction self help", {"Author": "Hector Garcia", "Format": "Hardcover", "Pages": "208", "Language": "English"}),
    ("Rich Dad Poor Dad by Robert Kiyosaki", "Rupa Publications", "Non Fiction", 499, 249, "hk_wall_shelves.png",
     "rich dad poor dad book finance non fiction", {"Author": "Robert T. Kiyosaki", "Format": "Paperback", "Pages": "336", "Language": "English"}),
    ("The Psychology of Money by Morgan Housel", "Jaico", "Non Fiction", 499, 274, "hk_wall_shelves.png",
     "psychology of money book finance non fiction", {"Author": "Morgan Housel", "Format": "Paperback", "Pages": "252", "Language": "English"}),
    ("Sapiens: A Brief History of Humankind", "HarperCollins", "Non Fiction", 899, 539, "hk_wall_shelves.png",
     "sapiens book history non fiction", {"Author": "Yuval Noah Harari", "Format": "Paperback", "Pages": "512", "Language": "English"}),
    ("The Alchemist by Paulo Coelho", "HarperCollins", "Fiction", 399, 219, "hk_wall_shelves.png",
     "alchemist book fiction paulo coelho", {"Author": "Paulo Coelho", "Format": "Paperback", "Pages": "208", "Language": "English"}),
    ("The Palace of Illusions by Chitra Banerjee", "Picador India", "Fiction", 499, 274, "hk_wall_shelves.png",
     "palace of illusions book fiction mythology", {"Author": "Chitra Banerjee Divakaruni", "Format": "Paperback", "Pages": "360", "Language": "English"}),
    ("Wings of Fire: An Autobiography of APJ Abdul Kalam", "Universities Press", "Non Fiction", 350, 192, "hk_wall_shelves.png",
     "wings of fire book biography kalam", {"Author": "A.P.J. Abdul Kalam", "Format": "Paperback", "Pages": "180", "Language": "English"}),
    ("Harry Potter and the Philosopher's Stone", "Bloomsbury", "Fiction", 599, 359, "hk_wall_shelves.png",
     "harry potter book fiction fantasy", {"Author": "J.K. Rowling", "Format": "Paperback", "Pages": "352", "Language": "English"}),
    ("NCERT Complete Guide Class 10 Mathematics", "Arihant", "Academic", 450, 315, "hk_wall_shelves.png",
     "ncert guide class 10 mathematics academic book", {"Board": "CBSE", "Class": "10", "Format": "Paperback", "Language": "English"}),
    ("Classmate Spiral Notebook Pack of 6 (300 Pages)", "Classmate", "Stationery", 660, 449, "hk_wall_shelves.png",
     "notebook classmate spiral stationery pack", {"Pack": "6 Notebooks", "Pages": "300 each", "Ruling": "Single Line", "Size": "A4"}),
    ("Faber-Castell 24 Shade Colour Pencil Set", "Faber-Castell", "Stationery", 320, 224, "hk_wall_shelves.png",
     "colour pencil faber castell stationery art set", {"Shades": "24", "Type": "Colour Pencils", "Length": "175mm", "Non-Toxic": "Yes"}),
]
