version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: buyzo_mysql
    restart: always
    environment:
      MYSQL_DATABASE: buyzo_db
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build: .
    container_name: buyzo_backend
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DB_ENGINE=mysql
      - DB_NAME=buyzo_db
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_HOST=db
      - DB_PORT=3306
      - DEBUG=True
    depends_on:
      - db

volumes:
  mysql_data:
