# Generated by Django 5.1.15 on 2026-08-22 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboundShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('destination_hub', models.CharField(max_length=150)),
                ('item_title', models.CharField(max_length=255)),
                ('sku', models.CharField(blank=True, max_length=60)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('courier_partner', models.CharField(default='BlueDart Express', max_length=100)),
                ('status', models.CharField(choices=[('Packing In Progress', 'Packing In Progress'), ('Ready for Pickup', 'Ready for Pickup'), ('Dispatched', 'Dispatched')], default='Packing In Progress', max_length=40)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'buyzo_outbound_shipments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('order_number', models.CharField(max_length=50)),
                ('customer_name', models.CharField(max_length=150)),
                ('item_title', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('reason', models.CharField(max_length=255)),
                ('condition', models.CharField(choices=[('Good Condition', 'Good Condition'), ('Damaged', 'Damaged')], default='Good Condition', max_length=50)),
                ('status', models.CharField(choices=[('Inspected', 'Inspected'), ('Restocked', 'Restocked'), ('Discarded', 'Discarded')], default='Inspected', max_length=40)),
                ('inspected_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'buyzo_returned_items',
                'ordering': ['-inspected_at'],
            },
        ),
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('source_warehouse', models.CharField(default='WH01 - Main Warehouse', max_length=100)),
                ('destination_warehouse', models.CharField(max_length=100)),
                ('item_title', models.CharField(max_length=255)),
                ('sku', models.CharField(blank=True, max_length=60)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('Initiated', 'Initiated'), ('In Transit', 'In Transit'), ('Completed', 'Completed')], default='Initiated', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'buyzo_stock_transfers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InboundReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('supplier_name', models.CharField(max_length=200)),
                ('item_title', models.CharField(max_length=255)),
                ('sku', models.CharField(blank=True, max_length=60)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('Pending Verification', 'Pending Verification'), ('Verified', 'Verified')], default='Pending Verification', max_length=30)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'buyzo_inbound_receipts',
                'ordering': ['-received_at'],
            },
        ),
    ]
