# Generated by Django 5.1.15 on 2026-08-26 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_herobanner'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse_code', models.CharField(default='WH01', max_length=40)),
                ('bin_location', models.CharField(blank=True, db_index=True, max_length=30)),
                ('total_units', models.PositiveIntegerField(default=0)),
                ('reserved_units', models.PositiveIntegerField(default=0)),
                ('in_transit_units', models.PositiveIntegerField(default=0)),
                ('reorder_level', models.PositiveIntegerField(default=10)),
                ('last_counted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_inventory', to='catalog.product')),
            ],
            options={
                'verbose_name_plural': 'Warehouse inventory',
                'db_table': 'buyzo_warehouse_inventory',
                'ordering': ['bin_location', 'id'],
            },
        ),
    ]
