# Generated by Django 5.1.15 on 2026-08-24 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Discover.\nShop. Save More.', max_length=200)),
                ('subtitle', models.TextField(default='Top brands, best prices & exclusive offers on every purchase.')),
                ('primary_button_text', models.CharField(default='Shop Now', max_length=50)),
                ('primary_button_link', models.CharField(default='electronics', max_length=100)),
                ('secondary_button_text', models.CharField(default='Explore Offers', max_length=50)),
                ('secondary_button_link', models.CharField(default='deals', max_length=100)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'buyzo_hero_banners',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
