# Generated by Django 5.1.15 on 2026-08-22 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentEarnings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_fee', models.DecimalField(decimal_places=2, default=50.0, max_digits=8)),
                ('tip', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('incentive', models.DecimalField(decimal_places=2, default=10.0, max_digits=8)),
                ('total_earned', models.DecimalField(decimal_places=2, default=60.0, max_digits=8)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_earnings', to='orders.order')),
            ],
            options={
                'db_table': 'buyzo_agent_earnings',
                'ordering': ['-earned_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('recipient_name', models.CharField(max_length=150)),
                ('recipient_phone', models.CharField(max_length=20)),
                ('delivery_address', models.CharField(max_length=255)),
                ('cod_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_cod_collected', models.BooleanField(default=False)),
                ('current_stage', models.PositiveSmallIntegerField(choices=[(1, 'Picked up from Warehouse'), (2, 'On the Way'), (3, 'Arrived at Destination'), (4, 'Delivered'), (5, 'Delivery Failed / Rescheduled')], default=1)),
                ('status', models.CharField(default='IN_TRANSIT', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_tasks', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_task', to='orders.order')),
            ],
            options={
                'db_table': 'buyzo_delivery_tasks',
                'ordering': ['-created_at'],
            },
        ),
    ]
