# Generated by Django 5.1.15 on 2026-08-31 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverytask',
            name='destination_latitude',
            field=models.DecimalField(decimal_places=6, default=19.076, max_digits=9),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='destination_longitude',
            field=models.DecimalField(decimal_places=6, default=72.8777, max_digits=9),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='failed_reason',
            field=models.CharField(blank=True, choices=[('CUSTOMER_UNAVAILABLE', 'Customer Unavailable / Unreachable'), ('WRONG_ADDRESS', 'Incorrect or Incomplete Address'), ('CUSTOMER_REJECTED', 'Customer Refused Delivery'), ('PARCEL_DAMAGED', 'Parcel Damaged in Transit'), ('COD_NOT_READY', 'COD Payment Not Ready'), ('CUSTOMER_REQUESTED_RESCHEDULE', 'Customer Requested Reschedule'), ('OTHER', 'Other Reason')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='pickup_latitude',
            field=models.DecimalField(decimal_places=6, default=19.088, max_digits=9),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='pickup_longitude',
            field=models.DecimalField(decimal_places=6, default=72.86, max_digits=9),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='rescheduled_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DeliveryAgentShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_status', models.CharField(choices=[('OFFLINE', 'Offline'), ('ONLINE', 'Online'), ('ON_BREAK', 'On Break')], default='OFFLINE', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('total_online_minutes', models.IntegerField(default=0)),
                ('current_latitude', models.DecimalField(decimal_places=6, default=19.076, max_digits=9)),
                ('current_longitude', models.DecimalField(decimal_places=6, default=72.8777, max_digits=9)),
                ('last_location_update', models.DateTimeField(auto_now=True)),
                ('cash_in_hand', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('max_cash_limit', models.DecimalField(decimal_places=2, default=10000.0, max_digits=10)),
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_shift', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'buyzo_delivery_agent_shifts',
            },
        ),
        migrations.CreateModel(
            name='DeliveryCashDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_mode', models.CharField(default='HUB_COUNTER', max_length=30)),
                ('status', models.CharField(default='COMPLETED', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('deposited_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_deposits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'buyzo_delivery_cash_deposits',
                'ordering': ['-deposited_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliverySOSAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('reason', models.CharField(default='ACCIDENT', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('status', models.CharField(choices=[('TRIGGERED', 'Emergency Triggered'), ('IN_PROGRESS', 'Responder Dispatched'), ('RESOLVED', 'Resolved')], default='TRIGGERED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sos_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'buyzo_delivery_sos_alerts',
                'ordering': ['-created_at'],
            },
        ),
    ]
