# Generated by Django 5.1.15 on 2026-08-31 05:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_deliverytask_destination_latitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryCashTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('transaction_type', models.CharField(choices=[('COLLECTION', 'Cash Collected from COD Delivery'), ('DEPOSIT', 'Cash Deposited at Hub'), ('REFUND', 'Refund / Return Adjustment'), ('ADJUSTMENT', 'Admin Balance Adjustment')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cash_in_hand_before', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cash_in_hand_after', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_transactions', to=settings.AUTH_USER_MODEL)),
                ('delivery_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_transactions', to='delivery.deliverytask')),
                ('deposit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_transactions', to='delivery.deliverycashdeposit')),
            ],
            options={
                'db_table': 'buyzo_delivery_cash_transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
