# Generated by Django 5.1.15 on 2026-08-31 05:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_deliverycashtransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryCashHandover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handover_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('confirmed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Handover Confirmation'), ('CONFIRMED', 'Confirmed & Received'), ('DISPUTED', 'Disputed Amount Discrepancy'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('dispute_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_handovers', to=settings.AUTH_USER_MODEL)),
                ('warehouse_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_cash_handovers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'buyzo_delivery_cash_handovers',
                'ordering': ['-created_at'],
            },
        ),
    ]
