# Generated by Django 5.1.15 on 2026-08-31 18:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_deliverycashhandover'),
        ('orders', '0002_order_cancellation_reason_order_cancelled_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentearnings',
            name='earned_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='agentearnings',
            index=models.Index(fields=['agent', '-earned_at'], name='buyzo_agent_agent_i_469629_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverytask',
            index=models.Index(fields=['agent', 'status'], name='buyzo_deliv_agent_i_36aecd_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverytask',
            index=models.Index(fields=['status', '-created_at'], name='buyzo_deliv_status_bd4e18_idx'),
        ),
    ]
