from django.urls import path
from .views import (
    DeliveryDashboardView,
    DeliveryTaskListView,
    DeliveryTaskUpdateView,
    AdvanceDeliveryStageView,
    VerifyDeliveryOTPView,
    AgentEarningsView,
    DeliveryHistoryView,
    DeliveryNotificationsView,
    DeliveryAgentProfileView,
    DeliverySupportView,
    CashTrackerView,
    CashDepositView,
    DeliveryCashTransactionsView,
    DeliveryCashReconciliationView,
    DeliveryCashHandoverRequestView,
    DeliveryShiftView,
    DeliveryShiftToggleView,
    DeliveryPerformanceView,
    DeliveryMapDataView,
    DeliveryLocationPingView,
    NextDeliveryQueueView,
    DeliveryWeatherView,
    DeliverySOSView,
    DeliveryTaskFailView,
    DeliveryPortalInitView,
)

urlpatterns = [
    path('portal-init/', DeliveryPortalInitView.as_view(), name='delivery_portal_init'),
    path('dashboard/', DeliveryDashboardView.as_view(), name='delivery_dashboard'),
    path('tasks/', DeliveryTaskListView.as_view(), name='delivery_tasks'),
    path('tasks/<str:task_id>/advance-stage/', AdvanceDeliveryStageView.as_view(), name='delivery_advance_stage'),
    path('tasks/<str:task_id>/verify-otp/', VerifyDeliveryOTPView.as_view(), name='delivery_verify_otp'),
    path('tasks/<str:task_id>/fail/', DeliveryTaskFailView.as_view(), name='delivery_task_fail'),
    path('tasks/<str:task_id>/', DeliveryTaskUpdateView.as_view(), name='delivery_task_update'),
    path('earnings/', AgentEarningsView.as_view(), name='delivery_earnings'),
    path('history/', DeliveryHistoryView.as_view(), name='delivery_history'),
    path('notifications/', DeliveryNotificationsView.as_view(), name='delivery_notifications'),
    path('profile/', DeliveryAgentProfileView.as_view(), name='delivery_profile'),
    path('support/', DeliverySupportView.as_view(), name='delivery_support'),

    # New Delivery Portal Functionalities
    path('cash-tracker/', CashTrackerView.as_view(), name='delivery_cash_tracker'),
    path('cash-deposit/', CashDepositView.as_view(), name='delivery_cash_deposit'),
    path('cash-transactions/', DeliveryCashTransactionsView.as_view(), name='delivery_cash_transactions'),
    path('cash-reconciliation/', DeliveryCashReconciliationView.as_view(), name='delivery_cash_reconciliation'),
    path('cash-handover/request/', DeliveryCashHandoverRequestView.as_view(), name='delivery_cash_handover_request'),
    path('cash-handover/my-requests/', DeliveryCashHandoverRequestView.as_view(), name='delivery_cash_handover_my_requests'),
    path('shift/', DeliveryShiftView.as_view(), name='delivery_shift'),
    path('shift/toggle/', DeliveryShiftToggleView.as_view(), name='delivery_shift_toggle'),
    path('performance/', DeliveryPerformanceView.as_view(), name='delivery_performance'),
    path('map-data/', DeliveryMapDataView.as_view(), name='delivery_map_data'),
    path('location-ping/', DeliveryLocationPingView.as_view(), name='delivery_location_ping'),
    path('queue/', NextDeliveryQueueView.as_view(), name='delivery_queue'),
    path('weather/', DeliveryWeatherView.as_view(), name='delivery_weather'),
    path('sos/', DeliverySOSView.as_view(), name='delivery_sos'),
]

